/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomaAmbosPositivos() {
        Library classUnderTest = new Library();
        assertEquals(19, classUnderTest.soma(10, 9));
    }
    
    @Test public void testSomaMaiorNegativo() {
        Library classUnderTest = new Library();
        assertEquals(-6, classUnderTest.soma(-10, 4));
    }
    
    @Test public void testSomaMaiorPositivo() {
        Library classUnderTest = new Library();
        assertEquals(8, classUnderTest.soma(15, -7));
    }
}
